import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Defines the sidebar configurations for all applications documented within the current website
 */
const sidebars: SidebarsConfig = {
  // The sidebar rendered for the tutorial on how to use the documentation website
  WordsSidebar: [
    {
      type: "autogenerated",
      dirName: "Words",
    },
  ],
};

export default sidebars;
